### ISSUE TITLE
Project Plan or Map

### ISSUE THREAD

**Issue by uncooloj** [PaystackHQ/reimbursement-app#1]
I would like to find out if there is a timeline/plan for this project or some sort of project map, as this looks interesting and is something i would like to jump on or work on provided there is a project map or plan.

Thanks

**Comment by onyekvchi** [comment]
Hey OJ!

Thanks for reaching out.

There’s currently no set roadmap / timeline for this project as I just make additions in my free time.

The plan is to complete the MVP, test it out at Paystack and make adjustments accordingly. I’m currently working on API to power the Vue app in this repo and I’m very open to contributions. Let me know in what capacity you'd like to contribute and we can hash out details from there.

Thanks again for reaching out.


Best regards,
Onyekachi.

**Comment by uncooloj** [comment]
Hello Kachi,

Can we draw up a flexible roadmap for it. I would like to know if it would be rolled out to the general public also. 

I can contribute to both the frontend and backend, i have done a run through of the Vue app and i can work with that. I would like to know what the backend is built with so i would know if i can work with you on that also.

Thanks for the reply

**Comment by uncooloj** [comment]
I also noticed the design framework used is that of Paystack so except there is a UI all set for the Product and maybe some Wireframes, i guess we'd have to draw that out.

Plus i personally think this product can be monetized

I would like to hear your thoughts on the above.

Thanks

**Comment by onyekvchi** [comment]
@uncooloj there's definitely a high chance of a general roll out and I'm building with that in mind, but ultimately that's @shollsman's prerogative as it's his idea originally. The current focus is to get it working for internal use at Paystack first.

Wrt what the backend will be built in, I'm currently using Ruby on Rails but I've barely written any code so I'm open to being convinced if you feel there's a better direction we can explore.

For your comment about the design framework (I'm not sure I understood you completely so please clarify if I'm answering the wrong thing): I've converted the mockups to the screens on the app already, so most of the work left on the UI front is to plug it in with the API and make sure it works as expected.

**Comment by uncooloj** [comment]
Thats fine, i would speak to @shollsman about that.

Since there are mockups, my question about design framework has been answered.

I dont actively do Ruby on Rails, but i have looked into it once, what other frameworks/languages do you work with for Backend? If there are others that i actively work with then we could agree on one of them, else i would brush up my Ruby on Rails, i have been looking for an opportunity to do that, so that works.

**Comment by uncooloj** [comment]
@onyekvchi So whats the way forward? 
Can we discuss further here on another platform, and what are we agreeing on for the backend?
